sudo: required

services:
  - docker

before_script:
  - env | grep TRAKT_ > .env

before_install:
  - docker pull TraktPHPApi/trakt-api

install:
  - docker-compose run trakt-api composer install --prefer-dist

script: vendor/bin/phpunit
